# Generated by Django 3.0.6 on 2020-10-19 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='categorie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
